version: "3"

services:
  database:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: "kimgangmin7259"
      MYSQL_DATABASE: "whether_etl"
  airflow-init:
    image: apache/airflow:2.9.3
    depends_on:
      - database
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+pymysql://root:kimgangmin7259@database:3306/whether_etl
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    command: airflow db init
  airflow-scheduler:
    image: apache/airflow:2.9.3
    depends_on:
      - airflow-init
    command: airflow scheduler
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+pymysql://root:kimgangmin7259@database:3306/whether_etl
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
  airflow-webserver:
    image: apache/airflow:2.9.3
    depends_on:
      - airflow-init
    command: airflow webserver
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+pymysql://root:kimgangmin7259@database:3306/whether_etl
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    
      

